server:
  port: 8081
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
#          enabled: true
#      routes:
#      - id: rest_service_route
#        uri: lb://rest_service
#        predicates:
#        - Path=/rest-service/**
#        filters:
#        - RewritePath=/rest-service/(?<path>.*), /$\{path}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:${HOST:localhost}}:${DISCOVERY_PORT:8761}/eureka/
      lease:
        duration: 5
ribbon:
  http:
    client:
      enabled: true